BOX_IMAGE = "centos/7"
NODE_COUNT = 2


Vagrant.configure("2") do |config|
   config.vm.provider "virtualbox" do |v|
     v.memory = 2048
  end

  config.vm.define "master" do |master|
    master.vm.box = BOX_IMAGE
    master.vm.network "private_network",  ip: "192.168.11.122"
    master.vm.provision "ansible" do |ansible|
        ansible.playbook = "k8play.yml"
        ansible.become = "true"
        ansible.verbose = "v"  
  end
 end
  
    config.vm.define "node1" do |node|
      node.vm.box = BOX_IMAGE
      node.vm.network "private_network", ip:"192.168.11.123"
      node.vm.provision "ansible" do |ansible|
           ansible.playbook = "k8node.yml"
           ansible.become = "true"
           ansible.verbose = "v"
       end
    end

    config.vm.define "node2" do |node|
      node.vm.box = BOX_IMAGE
      node.vm.network "private_network", ip: "192.168.11.124"
      node.vm.provision "ansible" do |ansible|
           ansible.playbook = "k8node.yml"
           ansible.become = "true"
           ansible.verbose = "v"
  end
end
end
